<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="context"
    nsURI="http://www.sourcepit.org/osgify/context/0.1" nsPrefix="ctx">
  <eClassifiers xsi:type="ecore:EClass" name="OsgifyContext" eSuperTypes="../../../../common-modeling/src/main/emf/common.ecore#//Extendable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundles" upperBound="-1"
        eType="#//BundleNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleNode" eSuperTypes="../../../../common-modeling/src/main/emf/common.ecore#//Extendable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        eType="ecore:EClass Java.ecore#//JavaPackageBundle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//BundleReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType ../../../../common-manifest/src/main/emf/manifest.ecore#//osgi/Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundleReference" eSuperTypes="../../../../common-modeling/src/main/emf/common.ecore#//Extendable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionRange" eType="ecore:EDataType ../../../../common-manifest/src/main/emf/manifest.ecore#//osgi/VersionRange"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//BundleNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="provided" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
